version: "3"
services:
  api-products:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev
