version: "3"
services:
  api-brands:
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.prod
    command:
      - npm run start
